### ISSUE TITLE
Update IPP Registry email archive references to instead reference new equivalent durable documents

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippregistry#1]
There are a number of references in the IPP Registry that point to the PWG mailing list archive for the ipp@pwg.org reflector. The contents of those email registrations have been captured in plain text files that have been placed in durable locations, to decouple the registry from the mail archive (which may change at some point in the future). The PWG's IPP Registration process document has been updated with this new system, including a naming scheme. The consensus is that these additions are accepted, so let's proceed with updating the registry.

Please update the links in the IPP Registry to point to these new durable links. The reference names could be updated, or just the URLs (you choose).

The mapping of old links to new durable links is in the attached "registration-mapping.txt" document.

[registration-mapping.txt](https://github.com/istopwg/ippregistry/files/3707231/registration-mapping.txt)

**Comment by michaelrsweet** [comment]
This has been submitted to IANA and is posted on the PWG web site.
