### ISSUE TITLE
Document-state enum spelled incorrectly as procesing instead of processing.

### ISSUE THREAD

**Issue by HPNavjot** [istopwg/ippregistry#3]
In latest IANA IPP registrations updated on 2024-06-13, we have observed that an enum attribute value is spelled incorrectly i.e., for document-state enum processing is spelled incorrectly.

It used to be _processing_ but now its misspelled as _procesing_.

![image](https://github.com/user-attachments/assets/d9cec7e8-a82b-43b0-a81e-00a1f75ccd47)

**Comment by HPNavjot** [comment]
@michaelrsweet the issue is still there in the latest spec released on 6th August 2024.

The spelling mistake now its _proccesing_ previous release it was _procesing_ but it should be **processing**

![image](https://github.com/user-attachments/assets/465cc9e4-9bb7-400d-bc65-33247bff54b2)

**Comment by michaelrsweet** [comment]
Re-submitted with (yet another) fix... :)
